stages:
  - lint
  - build
  - upload_nexus
  - release

variables:
  OUTPUT: "${CI_PROJECT_NAME}-linux-amd64"
  OUTPUT_AUDIO: "venova-audio-stream-linux-amd64"
  OUTPUT_WIN: "${CI_PROJECT_NAME}-windows-amd64.exe"
  OUTPUT_AUDIO_WIN: "venova-audio-stream-windows-amd64.exe"
  SOURCE_FILE: "cmd/${CI_PROJECT_NAME}/main.go"
  AUDIO_SOURCE_FILE: "cmd/audio-stream/main.go"

lint:
  image: "golang:latest"
  stage: "lint"
  script:
    - "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.5"
    - "golangci-lint --version"
    - "golangci-lint run"

build:
  image: "golang:latest"
  stage: build
  script:
    - "export GOMODCACHE=$(pwd)/go-mod-cache"
    - "export GOCACHE=$(pwd)/go-cache"
    - "export CGO_ENABLED=0"
# Windows
    - |
      GOOS=windows GOARCH=amd64 go build \
      -ldflags "\
      -X 'github.com/braydencw1/venova.NAME=venova' \
      -X 'github.com/braydencw1/venova.VERSION=${CI_COMMIT_TAG}' \
      -X 'github.com/braydencw1/venova.REVISION=${CI_COMMIT_SHORT_SHA}' \
      -X 'github.com/braydencw1/venova.REFERENCE=${CI_COMMIT_REF_NAME}' \
      -X 'github.com/braydencw1/venova.BUILT=${CI_PIPELINE_CREATED_AT}'" \
      -linkmode external \
      -extldflags="-static" \
      -o ${OUTPUT_WIN} ${SOURCE_FILE}
# Audio Windows
    - |
      GOOS=windows GOARCH=amd64 go build \
      -ldflags "\
      -X 'github.com/braydencw1/venova.NAME=venova-audio-stream' \
      -X 'github.com/braydencw1/venova.VERSION=${CI_COMMIT_TAG}' \
      -X 'github.com/braydencw1/venova.REVISION=${CI_COMMIT_SHORT_SHA}' \
      -X 'github.com/braydencw1/venova.REFERENCE=${CI_COMMIT_REF_NAME}' \
      -X 'github.com/braydencw1/venova.BUILT=${CI_PIPELINE_CREATED_AT}'" \
      -linkmode external \
      -extldflags="-static" \
      -o ${OUTPUT_AUDIO_WIN} ${AUDIO_SOURCE_FILE}
# Linux
    - |
      GOOS=linux GOARCH=amd64 go build \
      -ldflags "\
      -X 'github.com/braydencw1/venova.NAME=venova' \
      -X 'github.com/braydencw1/venova.VERSION=${CI_COMMIT_TAG}' \
      -X 'github.com/braydencw1/venova.REVISION=${CI_COMMIT_SHORT_SHA}' \
      -X 'github.com/braydencw1/venova.REFERENCE=${CI_COMMIT_REF_NAME}' \
      -X 'github.com/braydencw1/venova.BUILT=${CI_PIPELINE_CREATED_AT}'" \
      -linkmode external \
      -extldflags="-static" \
      -o ${OUTPUT} ${SOURCE_FILE}
    - ./${OUTPUT} -v
# Audio Linux
    - |
      GOOS=linux GOARCH=amd64 go build \
      -ldflags "\
      -X 'github.com/braydencw1/venova.NAME=venova-audio-stream' \
      -X 'github.com/braydencw1/venova.VERSION=${CI_COMMIT_TAG}' \
      -X 'github.com/braydencw1/venova.REVISION=${CI_COMMIT_SHORT_SHA}' \
      -X 'github.com/braydencw1/venova.REFERENCE=${CI_COMMIT_REF_NAME}' \
      -X 'github.com/braydencw1/venova.BUILT=${CI_PIPELINE_CREATED_AT}'" \
      -linkmode external \
      -extldflags="-static" \
      -o ${OUTPUT_AUDIO} ${AUDIO_SOURCE_FILE}
    - ./${OUTPUT_AUDIO} -v
  artifacts:
    paths:
      - "${OUTPUT}"
      - "${OUTPUT_WIN}"
      - "${OUTPUT_AUDIO}"
      - "${OUTPUT_AUDIO_WIN}"
  only:
    - tags

upload_nexus:
  image: "golang:latest"
  stage: upload_nexus
  script:
    - "curl -u ${NEXUS_USER}:${NEXUS_PASS} -k --upload-file ${OUTPUT} ${NEXUS_URL}${REPO_SUB_URL}/venova/linux/v${CI_COMMIT_TAG}/${OUTPUT}"
    - "curl -u ${NEXUS_USER}:${NEXUS_PASS} -k --upload-file ${OUTPUT} ${NEXUS_URL}${REPO_SUB_URL}/venova/windows/v${CI_COMMIT_TAG}/${OUTPUT}"
    - "curl -u ${NEXUS_USER}:${NEXUS_PASS} -k --upload-file ${OUTPUT} ${NEXUS_URL}${REPO_SUB_URL}/venova-audio-stream/linux/v${CI_COMMIT_TAG}/${OUTPUT_AUDIO}"
    - "curl -u ${NEXUS_USER}:${NEXUS_PASS} -k --upload-file ${OUTPUT} ${NEXUS_URL}${REPO_SUB_URL}/venova-audio-stream/windows/v${CI_COMMIT_TAG}/${OUTPUT_AUDIO_WIN}"
  artifacts:
    paths:
      - "${OUTPUT}"
      - "${OUTPUT_WIN}"
      - "${OUTPUT_AUDIO}"
      - "${OUTPUT_AUDIO_WIN}"
  only:
    - tags


release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  artifacts:
    paths:
      - "${OUTPUT}"
      - "${OUTPUT_WIN}"
  script:
    - echo "running release_job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    name: 'Release v$CI_COMMIT_TAG'
    assets:
      links:
        - name: "${OUTPUT}"
          url: "${CI_JOB_URL}/artifacts/file/${OUTPUT}"
        - name: "${OUTPUT_WIN}"
          url: "${CI_JOB_URL}/artifacts/file/${OUTPUT_WIN}"
        - name: "${OUTPUT_AUDIO}"
          url: "${CI_JOB_URL}/artifacts/file/${OUTPUT_AUDIO}"
        - name: "${OUTPUT_AUDIO_WIN}"
          url: "${CI_JOB_URL}/artifacts/file/${OUTPUT_AUDIO_WIN}"
